site_name: FreshRSS Documentation
theme: readthedocs
site_url: http://doc.freshrss.org
repo_url: https://github.com/FreshRSS/FreshRSS
docs_dir: .

pages:
- "Accueil": index.md
- "User Documentation":
    - "Installation": users/01_Installation.md
    - "First steps": users/02_First_steps.md
    - "Main view": users/03_Main_view.md
    - "Subscriptions": users/04_Subscriptions.md
    - "Configuration": users/05_Configuration.md
    - "Mobile applications": users/06_Mobile_access.md
    - "FAQ": users/07_Frequently_Asked_Questions.md
- "Developer documentation":
    - "First steps": developers/01_First_steps.md
    - "Github": developers/02_Github.md
    - "[Backend] Database schema": developers/03_Backend/01_Database_schema.md
    - "[Backend] Minz": developers/03_Backend/02_Minz.md
    - "[Backend] External librairies": developers/03_Backend/03_External_libraries.md
    - "[Backend] Changing source code": developers/03_Backend/04_Changing_source_code.md
    - "[Backend] Extensions": developers/03_Backend/05_Extensions.md
    - "[Frontend] View files": developers/04_Frontend/01_View_files.md
    - "[Frontend] Design": developers/04_Frontend/02_Design.md
- "Contributing to FreshRSS": contributing.md
